### ISSUE TITLE
Portability with other ics

### ISSUE THREAD

**Issue by dajawanaris** [alejoseb/Modbus-STM32-HAL-FreeRTOS#1]
Dear concern

As you have mentioned that the project is portable for all stm32, please specify how to open or use for my IC stm32f103c8tx. Im a bit new with cubemx so your helo would be grateful.

**Comment by alejoseb** [comment]
Hi, 
I recommend to use STM32 Cube IDE, which already includes CubeMX. I also provide an example here https://github.com/alejoseb/Modbus-STM32-HAL-FreeRTOS/tree/master/ModbusF103 that can work directly with your MCU.  You can compile that project and use the binary directly.
