### ISSUE TITLE
Rearrange UART interrupt callbacks

### ISSUE THREAD

**Issue by djuseeq** [alejoseb/Modbus-STM32-HAL-FreeRTOS#10]
Hi.
I mean is it possible to unify the two callback functions, put them in one file (RxCpltCallback is in Modbus.c)? This is not a vital problem, i have already make it for myself, because i use it with another library where i made it that way and i think it`s easier to exclude from build these source files and create a project related source file where we merge the two callback functions or do it in the main.c, and that way we don't have to touch the original source files. (UARTCallback.c). This is just my opinion, if for some reason is not right for You, then please let ignore it.
Thanks

**Comment by alejoseb** [comment]
Hi,
Yes I think that  helps. I moved the RX callback. TX and RX callbacks are now in the UARTCallback.c file. I also added the 
 portYIELD_FROM_ISR( xHigherPriorityTaskWoken ) line that was missed in the RX callback, you can check my latest commit.
