### ISSUE TITLE
Possible incorrect comment in ModbusStart function ?

### ISSUE THREAD

**Issue by alanbontoft** [alejoseb/Modbus-STM32-HAL-FreeRTOS#113]
Hi

Can you confirm if there is an error in the comment?  From the datasheet, low on DE puts transceiver in high impedance state, so this should read 'return RS485 transceiver to receive mode' ?

 // return RS485 transceiver to transmit mode
HAL_GPIO_WritePin(modH->EN_Port, modH->EN_Pin, GPIO_PIN_RESET);

**Comment by alejoseb** [comment]
Hi, yes the comment is wrong. Solved.
Thanks
