### ISSUE TITLE
No more than 61 registers are read by the 03 function

### ISSUE THREAD

**Issue by Andrew170285** [alejoseb/Modbus-STM32-HAL-FreeRTOS#116]
With function 03, only 61 registers are read per 1 request, if more, then an error. The problem is ModbusConfigTemplate.h line 27 #define MAX_BUFFER  128	    // Maximum size for the communication buffer in bytes.
According to the Modbus specification, no more than 252 bytes (126 registers) are counted per request. And the frame length is no more than 256 bytes. So the response is 1 byte(device address) + 1 byte(function) + 1 byte(data counter in bytes) + 250 bytes (data) + 2 bytes(CRC) = 255 bytes.
Solution: just increase the buffer to 255 for communication.
If I'm wrong, correct me, I'm a novice developer. It worked for me.

**Comment by alejoseb** [comment]
Hi you are right, but this is just a configuration parameter, thus you can increase your buffer size according to the Modbus standard if needed.
