### ISSUE TITLE
 How does this slave work? I've created a cluster according to the history, but modbuspoll doesn't connect.

### ISSUE THREAD

**Issue by Luxiangxianghy** [alejoseb/Modbus-STM32-HAL-FreeRTOS#119]
Please help me.

**Comment by alejoseb** [comment]
can you clarify what do you mean by a cluster or history?
You need to provide more details about your setup, and ask specific questions.
The slave works as any other Modbus compliant slave. I can't provide any other answer.

**Comment by alejoseb** [comment]
closing this issue since the question is the same in #118

**Comment by nirbhow** [comment]
@Luxiangxianghy can you provide me a little bit more detail to understand your set, might be possible i can help
1. how you are observing the master activity
2. what is status of modbusH.xbuffer and modbusH.u8buffer in your master and slave setup
