### ISSUE TITLE
RS485 dose not work for the second time

### ISSUE THREAD

**Issue by houchaoo** [alejoseb/Modbus-STM32-HAL-FreeRTOS#18]
the first time is ok ,the data is correct ,but another message does not resoponse

**Comment by alejoseb** [comment]
Hi,
I need more details about your issue, setup, hardware and software configuration. Otherwise, I cannot help you.
Thanks

**Comment by houchaoo** [comment]
Hi thanks for reply,my mcu is stm32f407vgt6, the 485 chip is ADM2587EBRWZ,the setting is like this below.


	ModbusH.uModbusType = MB_SLAVE;
	ModbusH.port = &huart3; // This is the UART port connected to STLINK in the NUCLEO F429
	ModbusH.u8id = 1; //slave ID
	ModbusH.u16timeOut = 1000;
	ModbusH.EN_Port = RS485_Ctrl_GPIO_Port;
	ModbusH.EN_Pin=RS485_Ctrl_Pin;
	//ModbusH2.EN_Port = LD2_GPIO_Port; // RS485 Enable
	//ModbusH2.EN_Pin = LD2_Pin; // RS485 Enable
	 ModbusH.xTypeHW = USART_HW;

	ModbusH.u16regs = ModbusDATA;
	ModbusH.u16regsize = sizeof(ModbusDATA) / sizeof(ModbusDATA[0]);
	//Initialize Modbus library
	ModbusInit(&ModbusH);
	//Start capturing traffic on serial Port
	ModbusStart(&ModbusH);



![image](https://user-images.githubusercontent.com/29146736/119850235-f2a9ef00-bf3f-11eb-9bc1-52abc8a2ddf4.png)


the first time when i send the read message ,i can get a reply form my mcu,however when i try to read again ,the mcu reply nothing,and another time i try to read ,the mcu works ok, and so on ....

**Comment by houchaoo** [comment]
![image](https://user-images.githubusercontent.com/29146736/119850992-9eebd580-bf40-11eb-8c9e-f335fca7b143.png)
![image](https://user-images.githubusercontent.com/29146736/119851059-add28800-bf40-11eb-82ed-f9b88aef1404.png)
![image](https://user-images.githubusercontent.com/29146736/119851421-f722d780-bf40-11eb-9467-f1620b699d76.png)
![image](https://user-images.githubusercontent.com/29146736/119851506-073ab700-bf41-11eb-8dc7-c55f68ecc034.png)
![image](https://user-images.githubusercontent.com/29146736/119851564-13267900-bf41-11eb-906e-d60b5c854b96.png)
![image](https://user-images.githubusercontent.com/29146736/119851608-1b7eb400-bf41-11eb-9d7c-36703e1f889f.png)

**Comment by houchaoo** [comment]
RS232 works fine..

**Comment by houchaoo** [comment]
I find that when i switch the RS485 ctrl pin ,I got a message "0x00" may be the 485 chip is not good . thanks a lot

**Comment by alejoseb** [comment]
Yes probably that is the problem. 
I have tested with transceivers MAX485 without any issue, I verified the control signal with an oscilloscope. 
I have also used the MAX1438, which does not require the control signal.

**Comment by houchaoo** [comment]
when I change the T35 from 5 to 6,the 485 works fine...thanks a lot ,Your project is wonderful

**Comment by alejoseb** [comment]
Glad to know this library is useful for your project, I will close this issue then.
