### ISSUE TITLE
can I set the retry times when the communication is lost ?

### ISSUE THREAD

**Issue by houchaoo** [alejoseb/Modbus-STM32-HAL-FreeRTOS#27]
it may be useful.

**Comment by alejoseb** [comment]
The retry option is not part of the Modbus master state diagram. Including it as part of the library will diverge from the standard. On the other hand, as part of the setup of the master you can  implement the retry option wrapping the Modbus request in a for loop and handling the exceptions on each failed retry. 

![master](https://user-images.githubusercontent.com/16860024/130106580-1a4ea96a-031a-4c99-be0c-1ae6ab44a6f5.png)
