### ISSUE TITLE
Would this work with UART interfaces on the STM32 (as opposed to USART)?

### ISSUE THREAD

**Issue by emptor8** [alejoseb/Modbus-STM32-HAL-FreeRTOS#39]
I'm seeing no response when I use a UART interface vs. a USART interface on the STM32. Is there anything special that needs to be done for it to work on a UART interface?

For example, using UARTx_RX/UARTx_TX pins rather than USARTx_RX/USART_TX pins

**Comment by NieLuc** [comment]
Did you find a solution?
