### ISSUE TITLE
Can't Unzip archive

### ISSUE THREAD

**Issue by antonbutenk** [alejoseb/Modbus-STM32-HAL-FreeRTOS#45]
Help me please. Downloaded archive need password to unzip. Do you know it?

**Comment by alejoseb** [comment]
The file has no password. Please use a different software like 7zip or clone the repository using directly git.

**Comment by antonbutenk** [comment]
Thanks a lot, 7Zip helps me.

**Comment by alejoseb** [comment]
No problem!
