### ISSUE TITLE
modbusHandler_t ModbusH;

### ISSUE THREAD

**Issue by elhamsut** [alejoseb/Modbus-STM32-HAL-FreeRTOS#46]
Can not instantiate an object from modbusHandler_t ?

**Comment by alejoseb** [comment]
This library is pure C code not C++.

**Comment by elhamsut** [comment]
How can I fix this issue?

**Comment by alejoseb** [comment]
There are plenty of options, you can look online how to use c from c++. Ultimately, you can write a class using the modbus structure and methods provided in this library. That will require considerable refactoring, which is beyond the scope of this library.
