### ISSUE TITLE
Using Modbus with lwip

### ISSUE THREAD

**Issue by Emreiris** [alejoseb/Modbus-STM32-HAL-FreeRTOS#5]
I have successfully implemented Modbus library and it is working properly in RTU_Slave mode. But when I try to add ethernet(TCP/IP), it fails. I can't even ping my device. I think the problem is task management. Ethernet manager task priority is Normal. what do you suggest to me?

**Comment by alejoseb** [comment]
The problem is too generic. I recommend checking your FreeRTOS configuration,  running out of heap is quite common. You can test your ethernet task alone without modbus, if that works I suspect you need to increment the heap.
