### ISSUE TITLE
install in keil

### ISSUE THREAD

**Issue by saeidshokoufi** [alejoseb/Modbus-STM32-HAL-FreeRTOS#54]
Dear Alejoseb

Thanks for your stm32 modbus Library.

Please tell how to install this library in keil.

Best Regards

**Comment by alejoseb** [comment]
Hi,
 I don't have access to the Keil compiler.
In general, what you need is a project template started by cubeMX  that configures a  USART peripheral including interrupts with the HAL library. Then add or copy the source code and header files of this Library. That should be enough to port any of the examples that I included in the repository.
