### ISSUE TITLE
Should the variable mHandlers be defined in modbus.h file?

### ISSUE THREAD

**Issue by kaidegit** [alejoseb/Modbus-STM32-HAL-FreeRTOS#55]
https://github.com/alejoseb/Modbus-STM32-HAL-FreeRTOS/blob/master/MODBUS-LIB/Inc/Modbus.h#L234

The definition in `modbus.h` causes some compilation errors like  `multiple definition of 'mHandlers'`.

May extern it in `modbus.h` and define it in `modbus.c`?

**Comment by alejoseb** [comment]
It is possible that those errors are reported depending on your particular environment and how the .h file is included. Your solution will work just fine.

**Comment by kaidegit** [comment]
I think it is very often to include `modbus.h` at least 2 times, one is in `modbus.c` and the other is where we use these modbus apis. So may it is ineluctable to cause `multiple definition of 'mHandlers'`.

**Comment by alejoseb** [comment]
I updated the library to solve this issue.
