### ISSUE TITLE
Unable to connect to ModBus Simulator

### ISSUE THREAD

**Issue by Ketul412** [alejoseb/Modbus-STM32-HAL-FreeRTOS#67]
I am at the very beginning of the STM journey and cannot figure out how to use this code. I did download the code on the Nucleo-F429ZI Board but now I am not able to connect the simulator you provided. Can you please help me out with any other configurations or connections required to board before running the simulator software?

**Comment by alejoseb** [comment]
I need more details. Are you testing the master or the slave? Depending on that you need to also select a master or slave simulator.

**Comment by Ketul412** [comment]
I want to use the simulator as a slave so can you walk me through the process to test the protocol.
Do I need to connect anything else to the board for the code to run?

**Comment by alejoseb** [comment]
Sorry, I cannot provide that kind of support.
