### ISSUE TITLE
How to write code multiple holding register

### ISSUE THREAD

**Issue by KomKGT** [alejoseb/Modbus-STM32-HAL-FreeRTOS#70]
Hello @alejoseb your library is well but I stuck about write code multiple holding register ,Can you give me an example Thank you.I add my code in picture 
![image](https://github.com/alejoseb/Modbus-STM32-HAL-FreeRTOS/assets/81642936/5104156a-0a6a-42e7-ab6e-deb25123e652)
it not work. What's wrong in my Code?

**Comment by alejoseb** [comment]
Hi, Check this example https://github.com/alejoseb/Modbus-STM32-HAL-FreeRTOS/blob/e9c16cf5a3e8fceb9ff06124b63ecf8fef9dc66c/Examples/ModbusF429/Core/Src/freertos.c#L120

It is for reading multiple registers, but the idea for writing is exactly the same

**Comment by KomKGT** [comment]
Thank you sir. I got it 
![image](https://github.com/alejoseb/Modbus-STM32-HAL-FreeRTOS/assets/81642936/7a54d9dd-61b0-468f-8c1a-9edadf6d98e7)
This is my code it's work.

**Comment by alejoseb** [comment]
I don't quite understand what you did, but I am glad it works for you.
