### ISSUE TITLE
~typo~ Supporting STM32G0

### ISSUE THREAD

**Issue by coratron** [alejoseb/Modbus-STM32-HAL-FreeRTOS#74]
line 1576 of Modbus.c should be changed to:

`while((modH->port->Instance->ISR & USART_ISR_TC) ==0 )`

from

`while((modH->port->Instance->SR & USART_SR_TC) ==0 )`

(At least for STM32G0)

**Comment by alejoseb** [comment]
Hi,
This is not a typo. Simply it requires updating the pre-processor directive according to the MCU family.
Please consider submitting a pull request adding that MCU family.
It should be something like this https://github.com/alejoseb/Modbus-STM32-HAL-FreeRTOS/pull/75/files/ddc474629f73a776debf0862f8cacf8ab8442d7b

**Comment by coratron** [comment]
Sounds - I will submit a PR, it's a simple addition and I can confirm it is working.
