### ISSUE TITLE
error: #20: identifier "UART_HandleTypeDef" is undefined， error: #20: identifier "GPIO_TypeDef" is undefined

### ISSUE THREAD

**Issue by Eric-Hsia** [alejoseb/Modbus-STM32-HAL-FreeRTOS#83]
hi, eziya, when I compile ModbusF429 example by keil mdk, there has undefined identifier errors, from the modbus.h headfile, it seems didn't include these two indentifier, thanks.
![image](https://github.com/alejoseb/Modbus-STM32-HAL-FreeRTOS/assets/20067709/7e7452b2-9615-4adb-af66-55bafebaebeb)

**Comment by Eric-Hsia** [comment]
hi,  when I compile ModbusF429 example by keil mdk, there has undefined identifier errors, from the modbus.h headfile, it seems didn't include these two indentifier, thanks.
![image](https://github.com/alejoseb/Modbus-STM32-HAL-FreeRTOS/assets/20067709/5cbacdb8-5065-41f5-80e1-0e40de1be2bb)

**Comment by alejoseb** [comment]
Hi, 
You need to update the include links accordingly. This is not a library issue, instead a configuration issue on your IDE.
