### ISSUE TITLE
Incorrect timeout between messages

### ISSUE THREAD

**Issue by ZaTeeman** [alejoseb/Modbus-STM32-HAL-FreeRTOS#88]
First of all thank you for your work

I am using modbus RTU master mode to communicate with several slaves.
boudrate: 115200
use DMA
microcontroller: stm32f407

Sometimes communication with some devices is lost.
As a result of searching for the reason, it was discovered that the library makes an insufficient period of silence between messages (for speed 115200, the standard provides for at least 1.75ms of silence)
![08912e08-f3f9-4401-a043-93cd087c9d33](https://github.com/alejoseb/Modbus-STM32-HAL-FreeRTOS/assets/58188750/aebe9bbe-4996-496b-9b95-88cba5202060)

I send messages from different threads using "ModbusQuery(&ModbusMaster, modbus_t_struct)"

Tell me how to set the correct silence time between messages?

**Comment by alejoseb** [comment]
hi, can you  explain what is the meaning of the trace in red? 
if that is the master, you have to add delays, (i.e.,  vtaskDelay) between calls to ModbusQuery.
