### ISSUE TITLE
Usage of portYieldFromISR() in Rx Callback

### ISSUE THREAD

**Issue by harish2297** [alejoseb/Modbus-STM32-HAL-FreeRTOS#9]
Will xTimerReset block RX interrupt ?
Should portYieldFromISR() should be in Rx Callback also ?

**Comment by alejoseb** [comment]
Hi,
>Will xTimerReset block RX interrupt ?
I am not sure what is your question. The RX interrupt can be block if the QueueModbusHandle is full, however that queue is processed continuously. 


>Should portYieldFromISR() should be in Rx Callback also ?
Yes you are right, I added portYieldFromISR() to the RX callback and moved it to the callbacks file.
